import 'package:flutter/material.dart';
import 'package:fusion_box/domain/entities/sprite_data.dart';

class SpriteFromSheet extends StatelessWidget {
  final SpriteData spriteData;
  final double? width;
  final double? height;
  final BoxFit fit;

  const SpriteFromSheet({
    super.key,
    required this.spriteData,
    this.width,
    this.height,
    this.fit = BoxFit.contain,
  });

  @override
  Widget build(BuildContext context) {
    if (spriteData.spriteBytes == null) {
      return Container(
        width: width ?? 64,
        height: height ?? 64,
        color: Colors.grey[300],
        child: const Icon(Icons.image_not_supported),
      );
    }

    Widget imageWidget = Image.memory(
      spriteData.spriteBytes!,
      width: width,
      height: height,
      fit: fit,
      errorBuilder: (context, error, stackTrace) {
        return Container(
          width: width ?? 64,
          height: height ?? 64,
          color: Colors.grey[300],
          child: const Icon(Icons.error),
        );
      },
    );

    // Aplicar filtro gris si es un sprite autogenerado
    if (spriteData.isAutogenerated) {
      imageWidget = ColorFiltered(
        colorFilter: const ColorFilter.matrix([
          0.6,
          0.2,
          0.2,
          0,
          0, // Red channel (reducido, con algo de los otros canales)
          0.2,
          0.6,
          0.2,
          0,
          0, // Green channel (reducido, con algo de los otros canales)
          0.2,
          0.2,
          0.6,
          0,
          0, // Blue channel (reducido, con algo de los otros canales)
          0, 0, 0, 1, 0, // Alpha channel (sin cambios)
        ]),
        child: imageWidget,
      );
    }

    return imageWidget;
  }
}
