// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHF5DMjRBejo--TDnFt_sQoschIsvcjWs',
    appId: '1:883854775572:web:0e993bb9f5753a8a861e01',
    messagingSenderId: '883854775572',
    projectId: 'fusion-box',
    authDomain: 'fusion-box.firebaseapp.com',
    storageBucket: 'fusion-box.firebasestorage.app',
    measurementId: 'G-RNLQEWTH2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmyQJ0Bz-UPqBMm_-w2_SkZ3gfYH3sR3w',
    appId: '1:883854775572:android:d56acbaad1fbc1d2861e01',
    messagingSenderId: '883854775572',
    projectId: 'fusion-box',
    storageBucket: 'fusion-box.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHF5DMjRBejo--TDnFt_sQoschIsvcjWs',
    appId: '1:883854775572:web:90a236b46bbe8a3b861e01',
    messagingSenderId: '883854775572',
    projectId: 'fusion-box',
    authDomain: 'fusion-box.firebaseapp.com',
    storageBucket: 'fusion-box.firebasestorage.app',
    measurementId: 'G-9ZCRVFM97C',
  );
}
