import 'package:flutter/material.dart';

/// Clase que contiene todas las constantes de colores utilizadas en la aplicación
class AppColors {
  AppColors._();

  // Colores principales de la aplicación
  static const Color primary = Colors.indigo;
  static const Color primaryDark = Color(0xFF303F9F);
  static const Color primaryLight = Color(0xFF7986CB);

  // Colores de fondo
  static const Color background = Colors.white;
  static const Color backgroundDark = Color(0xFF121212);
  static const Color surfaceBackground = Color(0xFFF5F5F5);

  // Colores de botones
  static const Color buttonPrimary = primary;
  static const Color buttonSecondary = Colors.grey;
  static const Color floatingButton = primary;
  static const Color secondaryButton = Colors.grey;

  // Colores de estado
  static const Color success = Colors.green;
  static const Color error = Colors.red;
  static const Color warning = Colors.orange;
  static const Color info = Colors.blue;

  // Colores de texto
  static const Color title = Colors.black;
  static const Color titleDark = Colors.white;
  static const Color subtitle = Color(0xFF666666);
  static const Color bodyText = Colors.black;
  static const Color bodyTextDark = Colors.white;
  static const Color caption = Color(0xFF999999);
  static const Color basicText = Colors.white;

  // Colores de AppBar
  static const Color appBar = primary;
  static const Color appBarDark = Color(0xFF1A1A1A);

  // Colores de la grid de fusiones
  static const Color headersBackground = Color(0xFF424242); // Colors.grey[800]
  static const Color fusionBackground = primaryDark; // Colors.indigo[800]
  static const Color sameFusionBackground = success; // Verde para fusiones AA
  static const Color fusionNotFoundBackground = Color(
    0xFFD32F2F,
  ); // Colors.red[800]
  static const Color autogeneratedFusionBackground = Color(
    0xFF616161,
  ); // Colors.grey[700]
  static const Color gridBorder = Color(0xFFE0E0E0); // Colors.grey[300]

  // Colores de sprites y elementos visuales
  static const Color spritePlaceholder = Color(
    0xFFE1BEE7,
  ); // Colors.purple[100]
  static const Color spritePlaceholderBorder = Color(
    0xFFBA68C8,
  ); // Colors.purple[300]
  static const Color spritePlaceholderIcon = Colors.purple;
  static const Color autogeneratedIcon = warning;
  static const Color autogeneratedText = Color(
    0xFFE65100,
  ); // Colors.orange[700]

  // Colores de overlay y transparencias
  static const Color overlayLight = Color(
    0x1A000000,
  ); // Colors.black.withValues(alpha: 0.1)
  static const Color overlayMedium = Color(
    0x4D000000,
  ); // Colors.black.withValues(alpha: 0.3)
  static const Color overlayDark = Color(
    0x80000000,
  ); // Colors.black.withValues(alpha: 0.5)
  static const Color overlayGrey = Color(
    0x4D9E9E9E,
  ); // Colors.grey.withValues(alpha: 0.3)

  // Colores de selección y focus
  static const Color selectionBackground = Color(
    0x1A2196F3,
  ); // Colors.blue.withAlpha(25)
  static const Color selectionBorder = Color(
    0x4D2196F3,
  ); // Colors.blue.withAlpha(77)
  static const Color selectionIcon = Color(0xFF1976D2); // Colors.blue[700]

  // Colores de loading y estados de carga
  static const Color loadingBackground = overlayDark;
  static const Color loadingText = basicText;
  static const Color loadingIcon = Color(0xFF757575); // Colors.grey[600]
  static const Color loadingIconSecondary = Color(
    0xFF9E9E9E,
  ); // Colors.grey[500]

  // Colores de cards y contenedores
  static const Color cardBackground = background;
  static const Color cardBackgroundDark = Color(0xFF2D2D2D);
  static const Color cardBorder = gridBorder;

  // Colores de diálogos y modales
  static const Color dialogBackground = background;
  static const Color dialogBackgroundDark = cardBackgroundDark;

  // Colores de snackbars
  static const Color snackbarSuccess = success;
  static const Color snackbarError = error;
  static const Color snackbarWarning = warning;
  static const Color snackbarInfo = info;

  // Colores de iconos
  static const Color iconPrimary = title;
  static const Color iconPrimaryDark = titleDark;
  static const Color iconSecondary = Color(0xFF757575); // Colors.grey[600]
  static const Color iconSecondaryDark = Color(0xFF9E9E9E); // Colors.grey[500]
  static const Color iconDisabled = Color(0xFFBDBDBD); // Colors.grey[400]

  // Colores de divisores y líneas
  static const Color divider = gridBorder;

  // Colores de sombras
  static const Color shadow = overlayLight;
  static const Color shadowDark = overlayMedium;

  // Colores de Pokemon (ya definidos en pokemon_type_colors.dart)
  static const Color pokemonDefaultType = Color(0xFFA8A878);
  static const Color pokemonBorder = Colors.white;
  static const Color pokemonShadow = overlayLight;

  // Colores de autogeneración
  static const Color autogeneratedTextLight = Color(
    0xFFE0E0E0,
  ); // Colors.grey[300]
  static const Color autogeneratedTextDark = Color(
    0xFFBDBDBD,
  ); // Colors.grey[400]
  static const Color autogeneratedTypes = iconSecondary;

  // Colores de error y estados especiales
  static const Color errorBackground = Color(
    0x1AFF0000,
  ); // Colors.red.withValues(alpha: 0.1)
  static const Color errorBorder = Color(
    0x4DFF0000,
  ); // Colors.red.withValues(alpha: 0.3)
  static const Color errorText = error;
  static const Color errorIcon = error;

  // Colores de información y ayuda
  static const Color infoBackground = Color(
    0x1A2196F3,
  ); // Colors.blue.withValues(alpha: 0.1)
  static const Color infoBorder = Color(
    0x4D2196F3,
  ); // Colors.blue.withValues(alpha: 0.3)
  static const Color infoText = Color(0xFF1976D2); // Colors.blue[700]
  static const Color infoIcon = infoText;

  // Colores de éxito
  static const Color successBackground = Color(
    0x1A4CAF50,
  ); // Colors.green.withValues(alpha: 0.1)
  static const Color successBorder = Color(
    0x4D4CAF50,
  ); // Colors.green.withValues(alpha: 0.3)
  static const Color successText = success;
  static const Color successIcon = success;

  // Colores de advertencia
  static const Color warningBackground = Color(
    0x1AFF9800,
  ); // Colors.orange.withValues(alpha: 0.1)
  static const Color warningBorder = Color(
    0x4DFF9800,
  ); // Colors.orange.withValues(alpha: 0.3)
  static const Color warningText = warning;
  static const Color warningIcon = warning;

  // Colores de overlay oscuro para modales
  static const Color modalOverlay = Color(
    0xD9000000,
  ); // Colors.black.withValues(alpha: 0.85)
  static const Color modalOverlayLight = overlayDark;

  // Colores de scroll y indicadores
  static const Color scrollIndicator = iconDisabled;
  static const Color scrollIndicatorDark = Color(
    0xFF616161,
  ); // Colors.grey[700]
  static const Color scrollTrack = surfaceBackground;
  static const Color scrollTrackDark = Color(0xFF2D2D2D);

  // Colores de tooltip
  static const Color tooltipBackground = headersBackground;
  static const Color tooltipText = Colors.white;

  // Colores de badge y notificaciones
  static const Color badgeBackground = error;
  static const Color badgeText = Colors.white;
  static const Color notificationBackground = info;
  static const Color notificationText = Colors.white;

  // Colores de progreso
  static const Color progressBackground = gridBorder;
  static const Color progressValue = primary;
  static const Color progressValueSuccess = success;
  static const Color progressValueError = error;
  static const Color progressValueWarning = warning;

  // Colores de switch y toggle
  static const Color switchActive = primary;
  static const Color switchInactive = iconDisabled;
  static const Color switchTrack = gridBorder;

  // Colores de checkbox y radio
  static const Color checkboxActive = primary;
  static const Color checkboxInactive = iconDisabled;
  static const Color checkboxBorder = iconSecondary;

  // Colores de slider
  static const Color sliderActive = primary;
  static const Color sliderInactive = gridBorder;
  static const Color sliderThumb = primary;

  // Colores de input y campos de texto
  static const Color inputBorder = gridBorder;
  static const Color inputBorderFocused = primary;
  static const Color inputBorderError = error;
  static const Color inputBackground = background;
  static const Color inputBackgroundDark = cardBackgroundDark;
  static const Color inputText = bodyText;
  static const Color inputTextDark = bodyTextDark;
  static const Color inputPlaceholder = Color(0xFF9E9E9E); // Colors.grey[500]
  static const Color inputPlaceholderDark = iconSecondary;

  // Colores de tabla
  static const Color tableHeader = headersBackground;
  static const Color tableRow = background;
  static const Color tableRowAlternate = surfaceBackground;
  static const Color tableBorder = gridBorder;
  static const Color tableText = bodyText;
  static const Color tableTextHeader = Colors.white;

  // Colores de navegación
  static const Color navigationBar = background;
  static const Color navigationBarDark = Color(0xFF1A1A1A);
  static const Color navigationItem = bodyText;
  static const Color navigationItemDark = bodyTextDark;
  static const Color navigationItemSelected = primary;
  static const Color navigationItemSelectedDark = primaryLight;

  // Colores de drawer y sidebar
  static const Color drawerBackground = background;
  static const Color drawerBackgroundDark = cardBackgroundDark;
  static const Color drawerHeader = headersBackground;
  static const Color drawerHeaderDark = navigationBarDark;

  // Colores de bottom sheet
  static const Color bottomSheetBackground = background;
  static const Color bottomSheetBackgroundDark = cardBackgroundDark;
  static const Color bottomSheetHandle = iconDisabled;

  // Colores de expansion panel
  static const Color expansionPanelHeader = surfaceBackground;
  static const Color expansionPanelHeaderDark = headersBackground;
  static const Color expansionPanelContent = background;
  static const Color expansionPanelContentDark = cardBackgroundDark;

  // Colores de stepper
  static const Color stepperActive = primary;
  static const Color stepperInactive = iconDisabled;
  static const Color stepperCompleted = success;
  static const Color stepperError = error;

  // Colores de chip
  static const Color chipBackground = gridBorder;
  static const Color chipBackgroundSelected = primary;
  static const Color chipText = bodyText;
  static const Color chipTextSelected = Colors.white;
  static const Color chipDeleteIcon = iconSecondary;

  // Colores de avatar
  static const Color avatarBackground = gridBorder;
  static const Color avatarText = iconSecondary;

  // Colores de list tile
  static const Color listTileBackground = background;
  static const Color listTileBackgroundDark = cardBackgroundDark;
  static const Color listTileSelected = Color(0xFFE3F2FD); // Colors.blue[50]
  static const Color listTileSelectedDark = Color(
    0xFF1A237E,
  ); // Colors.indigo[900]

  // Colores de fab (Floating Action Button)
  static const Color fabBackground = primary;
  static const Color fabIcon = Colors.white;
  static const Color fabExtendedBackground = primary;
  static const Color fabExtendedText = basicText;

  // Colores de back button
  static const Color backButton = bodyText;
  static const Color backButtonDark = bodyTextDark;

  // Colores de close button
  static const Color closeButton = iconSecondary;
  static const Color closeButtonDark = iconSecondaryDark;

  // Colores de refresh indicator
  static const Color refreshIndicator = primary;
  static const Color refreshIndicatorBackground = Color(
    0xFFE3F2FD,
  ); // Colors.blue[50]

  // Colores de shimmer loading
  static const Color shimmerBase = gridBorder;
  static const Color shimmerHighlight = surfaceBackground;

  // Colores de skeleton loading
  static const Color skeletonBackground = gridBorder;
  static const Color skeletonShimmer = surfaceBackground;

  // Colores de empty state
  static const Color emptyStateIcon = iconDisabled;
  static const Color emptyStateText = iconSecondary;

  // Colores de offline indicator
  static const Color offlineBackground = error;
  static const Color offlineText = Colors.white;

  // Colores de version y build info
  static const Color versionText = inputPlaceholder;
  static const Color buildInfoText = iconDisabled;

  // Colores de debug
  static const Color debugBackground = Color(0xFFFFEB3B); // Colors.yellow
  static const Color debugText = bodyText;
  static const Color debugBorder = Color(0xFFFFC107); // Colors.amber

  // Colores de entorno
  static const Color developmentBackground = success;
  static const Color developmentText = basicText;
  static const Color productionBackground = info;
  static const Color productionText = basicText;
  static const Color stagingBackground = warning;
  static const Color stagingText = basicText;
  static const Color testingBackground = Color(0xFF9C27B0); // Colors.purple
  static const Color testingText = basicText;
}
